#! /usr/bin/env python
import os
import json
import subprocess
import shutil
import pandas as pd
import numpy as np

"""
run EpitopeScan tests on sample peptide sequences
"""

def LoadOutput(out_dir):
	"""
	Load output tables from a directory

	out_dir - str, path to EpitopeScan output directory
	"""

	name = out_dir[3:]

	mut_data  = pd.read_csv(f"{out_dir}/{name}_mutation_data.tsv", sep='\t', index_col=0)
	NA_matrix = pd.read_csv(f"{out_dir}/{name}_NA_mutation_matrix.csv", index_col=0)
	AA_matrix = pd.read_csv(f"{out_dir}/{name}_AA_mutation_matrix.csv", index_col=0)

	return mut_data, NA_matrix, AA_matrix

def CompareMutationData(mut_df, ref_data, ambiguity_intolerance=False):
	"""
	Perform comparison between reference mutation data and data in EpitopeScan

	mut_df - pd.DataFrame, mutation data generated by EpitopeScan
	ref_data - dict, reference mutation data for these samples

	returns:
	list, data on samples with detected mismatches
	"""
	
	mismatched_samples = []

	for _, row in mut_df.iterrows():
		
		name = row['sequence_name']

		if row['NA_mutations'] == 'NF':
			if not ref_data[name]['non_functional']:
				mismatched_samples.append(name)
				print(f"{name} reported as NF, when it is not")

		elif row['NA_mutations'] == '-':
			if not ref_data[name]['no_coverage']:
				if ambiguity_intolerance and ref_data[name]['has_ambiguity']:
					continue
				else: 
					mismatched_samples.append(name)
					print(f"{name} reported as no coverage, when it should not")
		else:

			if ref_data[name]['non_functional']:
				mismatched_samples.append(name)
				print(f"{name} not reported as NF")

			elif ref_data[name]['no_coverage']:
				mismatched_samples.append(name)
				print(ref_data[name]['no_coverage'])
				print(f"{name} not reported as no coverage")

			elif row['NA_mutations'] is np.nan:
				if not len(ref_data[name]['NA_mutations']) == 0:
					mismatched_samples.append(name)
					print(f"{name} has mutations when none expected")

			elif row['AA_mutations'] is np.nan:
				if not len(ref_data[name]['AA_mutations']) == 0:
					mismatched_samples.append(name)
					print(f"{name} has mutations when none expected")

			else:
				NA_mutations = set(row['NA_mutations'].split(','))
				AA_mutations = set(row['AA_mutations'].split(','))
				if NA_mutations != set(ref_data[name]['NA_mutations']):
					print(f"{name} NA mutation mismatch:", NA_mutations, ' ', ref_data[name]['NA_mutations'])
					mismatched_samples.append(name)
				if AA_mutations != set(ref_data[name]['AA_mutations']):
					print(f"{name} AA mutation mismatch:", AA_mutations, ' ', ref_data[name]['AA_mutations'])
					mismatched_samples.append(name)

	return mismatched_samples

if __name__ == "__main__":

	#### list peptides to run tests on 
	script_dir = os.path.realpath(os.path.dirname(__file__))

	# list folders with peptide data
	peptide_names = [f for f in os.listdir(script_dir) if f[0] == 'T']

	# read peptide sequences
	test_peptides = []
	for peptide_name in peptide_names:
		seq = ''.join(pd.read_csv(f"{script_dir}/{peptide_name}/{peptide_name}_AA_mutation_matrix.csv", index_col=0).index)
		test_peptides.append(seq)

	# run tests for each peptide in test dir
	for name, peptide in zip(peptide_names, test_peptides):

		print(f"Running tests on peptide {name} {peptide}\n")

		# load reference data
		with open(f'{script_dir}/{name}/{name}_ref_data.json') as json_file:
			ref_data = json.load(json_file)
		ref_NA_matrix = pd.read_csv(f"{script_dir}/{name}/{name}_NA_mutation_matrix.csv", index_col=0)
		ref_AA_matrix = pd.read_csv(f"{script_dir}/{name}/{name}_AA_mutation_matrix.csv", index_col=0)
		
		### TEST 1 ###
		# default run options

		print(f"Running test 1...")

		# run analysis at default parameters
		subprocess.run([f"EpitopeScan", "scan",
						"-e", f"{name},{peptide}",
						"--msa", f"{script_dir}/{name}/{name}_test_sequences.fasta",
						"-o", f"ES_{name}"],
						stdout=subprocess.DEVNULL)


		# load output
		mut_data, NA_matrix, AA_matrix = LoadOutput(f"ES_{name}")

		# compare count matrices
		NA_count_comparison = NA_matrix.compare(ref_NA_matrix)
		AA_count_comparison = AA_matrix.compare(ref_AA_matrix)

		# compare mutation matrices
		mistmatches = CompareMutationData(mut_data, ref_data)

		# print results
		if (len(mistmatches) == 0) and NA_count_comparison.empty and AA_count_comparison.empty:
			print("Test passed\n")
		else:
			print("Test failed!\n")
		############

		### TEST 2 ###
		# quality filtering

		print(f"Running test 2...")

		# run analysis with quality filter
		subprocess.run([f"EpitopeScan", "scan",
						"-e", f"{name},{peptide}",
						"--msa", f"{script_dir}/{name}/{name}_test_sequences.fasta",
						"-q", "0.05",
						"-o", f"ES_{name}"],
						stdout=subprocess.DEVNULL)


		# load output
		mut_data, NA_matrix, AA_matrix = LoadOutput(f"ES_{name}")

		# check that all samples are correctly filtered
		should_be_kept1 = set()
		for seq_name in ref_data:
			if not ref_data[seq_name]['high_N_content']:
				should_be_kept1.add(seq_name)
		processed_samples1 = set(mut_data['sequence_name'])

		# this should return all samples
		subprocess.run([f"EpitopeScan", "scan",
						"-e", f"{name},{peptide}",
						"--msa", f"{script_dir}/{name}/{name}_test_sequences.fasta",
						"-q", "0.30",
						"-o", f"ES_{name}"],
						stdout=subprocess.DEVNULL)


		# load output
		mut_data, NA_matrix, AA_matrix = LoadOutput(f"ES_{name}")

		# check that all samples are correctly filtered
		should_be_kept2 = set()
		for seq_name in ref_data:
			should_be_kept2.add(seq_name)
		processed_samples2 = set(mut_data['sequence_name'])

		if (processed_samples1 == should_be_kept1) and \
		   (processed_samples2 == should_be_kept2):
			print('Test passed\n')
		else:
			print("Test failed!\n")
		############

		### TEST 3 ###
		# ambiguity intolerance 
		
		print(f"Running test 3...")

		# run analysis with ambiguity intolerance
		subprocess.run([f"EpitopeScan", "scan",
						"-e", f"{name},{peptide}",
						"--msa", f"{script_dir}/{name}/{name}_test_sequences.fasta",
						"-n 0.0",
						"-o", f"ES_{name}"],
						stdout=subprocess.DEVNULL)


		# load output
		mut_data, NA_matrix, AA_matrix = LoadOutput(f"ES_{name}")

		# compare mutation matrices
		mistmatches = CompareMutationData(mut_data, ref_data, ambiguity_intolerance=True)

		if len(mistmatches) == 0:
			print("Test passed\n")
		else:
			print("Test failed!\n")
		############

		# delete output for this peptide
		shutil.rmtree(f'ES_{name}')












